### ISSUE TITLE
Third party login ? More informations  ? 

### ISSUE THREAD

**Issue by BourAbdelhadi** [baijunyao/thinkphp-bjyblog#2]
Hello , 

Well , first of all i want to thank you for the hard work , I liked your blog so much , I've one question if you don't mind ! 

I want to modify the Third party login , i want to use only Facebook & Github , could you please guide me to find the path to modify these things ?

**Comment by baijunyao** [comment]
No problem.  

If you can read Chinese, add github and google is simple, but without Facebook, you can refer to [ThinkSDK](https://github.com/baijunyao/ThinkSDK) to add Facebook.  

By the way, I recommend you use [laravel-bjyblog](https://github.com/baijunyao/laravel-bjyblog),It is using laravel to develop the blog, laravel-bjyblog is the same as the thinkphp-bjyblog page, laravel-bjyblog uses [socialite](https://socialiteproviders.github.io/), it has all the third party login.

If you do not know how to use ThinkSDK to add Facebook, or do not know how to install laravel-bjyblog, I can guide you.
